version: "3"

services:
    app:
        build:
            context: docker/dev
        depends_on:
            - db
        ports:
            - "8080:8080"
            - "8000:8000"
            - "3000:3000"
        volumes:
            - ./app:/app
        environment:
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
        links:
            - db

    db:
        image: postgres:10.1
        ports:
            - "5432:5432"
        environment:
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - DB_NAME=${DB_NAME}
        volumes:
            - ./data/postgres/data:/var/lib/postgresql/data